name: npm publish

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          cache: yarn

      - run: yarn && yarn tsc -d

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
